# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.

# The CMake executable.
CMAKE_COMMAND = /data/data/ru.iiec.cxxdroid/files/bin/cmake

# The command to remove a file.
RM = /data/data/ru.iiec.cxxdroid/files/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /storage/emulated/0/Android/data/ru.iiec.cxxdroid/files/midnight_movies

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /storage/emulated/0/Android/data/ru.iiec.cxxdroid/files/midnight_movies

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/Android/data/ru.iiec.cxxdroid/files/midnight_movies/CMakeFiles /storage/emulated/0/Android/data/ru.iiec.cxxdroid/files/midnight_movies//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/Android/data/ru.iiec.cxxdroid/files/midnight_movies/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named midnight_movies

# Build rule for target.
midnight_movies: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 midnight_movies
.PHONY : midnight_movies

# fast build rule for target.
midnight_movies/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/build
.PHONY : midnight_movies/fast

src/cast.o: src/cast.cpp.o
.PHONY : src/cast.o

# target to build an object file
src/cast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/src/cast.cpp.o
.PHONY : src/cast.cpp.o

src/cast.i: src/cast.cpp.i
.PHONY : src/cast.i

# target to preprocess a source file
src/cast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/src/cast.cpp.i
.PHONY : src/cast.cpp.i

src/cast.s: src/cast.cpp.s
.PHONY : src/cast.s

# target to generate assembly for a file
src/cast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/src/cast.cpp.s
.PHONY : src/cast.cpp.s

src/director.o: src/director.cpp.o
.PHONY : src/director.o

# target to build an object file
src/director.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/src/director.cpp.o
.PHONY : src/director.cpp.o

src/director.i: src/director.cpp.i
.PHONY : src/director.i

# target to preprocess a source file
src/director.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/src/director.cpp.i
.PHONY : src/director.cpp.i

src/director.s: src/director.cpp.s
.PHONY : src/director.s

# target to generate assembly for a file
src/director.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/src/director.cpp.s
.PHONY : src/director.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/titles.o: src/titles.cpp.o
.PHONY : src/titles.o

# target to build an object file
src/titles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/src/titles.cpp.o
.PHONY : src/titles.cpp.o

src/titles.i: src/titles.cpp.i
.PHONY : src/titles.i

# target to preprocess a source file
src/titles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/src/titles.cpp.i
.PHONY : src/titles.cpp.i

src/titles.s: src/titles.cpp.s
.PHONY : src/titles.s

# target to generate assembly for a file
src/titles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/src/titles.cpp.s
.PHONY : src/titles.cpp.s

src/writer.o: src/writer.cpp.o
.PHONY : src/writer.o

# target to build an object file
src/writer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/src/writer.cpp.o
.PHONY : src/writer.cpp.o

src/writer.i: src/writer.cpp.i
.PHONY : src/writer.i

# target to preprocess a source file
src/writer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/src/writer.cpp.i
.PHONY : src/writer.cpp.i

src/writer.s: src/writer.cpp.s
.PHONY : src/writer.s

# target to generate assembly for a file
src/writer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/midnight_movies.dir/build.make CMakeFiles/midnight_movies.dir/src/writer.cpp.s
.PHONY : src/writer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... midnight_movies"
	@echo "... src/cast.o"
	@echo "... src/cast.i"
	@echo "... src/cast.s"
	@echo "... src/director.o"
	@echo "... src/director.i"
	@echo "... src/director.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/titles.o"
	@echo "... src/titles.i"
	@echo "... src/titles.s"
	@echo "... src/writer.o"
	@echo "... src/writer.i"
	@echo "... src/writer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

