#include <iostream>
#include <vector>
#include "conio.h"

using namespace std;

class Titles
{
  public:
    string title;
    vector<string> part000{
        "danger!",
        "they are here!",
        "haunted by",
        "attack of",
        "how they run -",
        "hell of the",
        "terror of the",
        "beware! they come -",
        "caution! they come -",
        "in the death grip of the",
        "my neighbors are",
        "lord of the",
        "manhunt -",
        "after sunse -",
        "blood fight -",
        "voodoo -",
        "death sword of the",
        "highway of the",
        "tunnel of the",
        "valley of the",
        "hills of the",
        "catacombs of the",
        "campfire tales -",
        "in the purgatory of the",
        "kill the",
        "e:xecutioner of the",
        "night of the",
        "rise of the",
        "curse of the",
        "cult of the",
        "island of the",
        "jungle of the",
        "school of the",
        "day of the",
        "dawn of the",
        "land of the",
        "army of the",
        "the cop & the",
        "werewolf cop vs.",
        "immortal man vs.",
        "iron fist vs.",
        "pope vs.",
        "bigfoot vs.",
        "kickboxers vs.",
        "cowboys vs.",
        "black phantom vs.",
        "invasion of the",
        "summer camp of the",
        "blood circle of the",
        "blood court of the",
        "naked under",
        "planet of the",
        "cemetery of the"};
    vector<string> part001{
        "funky",
        "deadly",
        "scary",
        "evil",
        "flesh eating",
        "big tits",
        "big ass",
        "nude",
        "sexy",
        "bloody",
        "undead",
        "nymphomaniac",
        "bloodsucking",
        "maniac",
        "headless",
        "giant",
        "psycho",
        "teenage"};
    vector<string> part002{
        "alien",
        "clone",
        "ultra",
        "cosmic",
        "mecha",
        "karate",
        "kung-fu",
        "surf",
        "killer",
        "slave",
        "robo"};
    vector<string> part003{
        "brain suckers",
        "superheroes",
        "caveman",
        "kickboxers",
        "demons",
        "babes",
        "doctors",
        "twins",
        "witches",
        "dolls",
        "snowmans",
        "clowns",
        "barbarians",
        "terrorists",
        "cultists",
        "zcmbies",
        "bikers",
        "killers",
        "nuns",
        "freaks",
        "cheerleaders",
        "virgins",
        "strippers",
        "schoolgirls",
        "mutans",
        "ninjas",
        "nazis",
        "girls",
        "vampires",
        "clowns",
        "cannibals",
        "she-devils",
        "whores",
        "geishas",
        "yakuzas"};
    vector<string> part004{
        "in straitjackets",
        "in chains",
        "from the future",
        "on wheels",
        "from the abyss",
        "from hell",
        "from outer space",
        "from beyond",
        "from the darkness",
        "from the deep",
        "on their hell bikes",
        "on their rocket surfboards",
        "from mars",
        "from planet x",
        "at midnight"};
    vector<string> part005{
        "- the musical",
        "- the awakening",
        "- the return",
        "- remake",
        "- the revenge",
        "- a new beginning",
        "- resurrection",
        "- the next chapter",
        "- the final chapter",
        "- new blood",
        "- the new generation",
        "3D",
        "- part ii",
        "- part iii",
        "- part iv",
        "- part v",
        "- part vi"};
        
        void create();
        void output();
};